### ISSUE TITLE
Improving the JSDoc types and generating a declaration file

### ISSUE THREAD

**Issue by johnhooks** [aduth/hpq#17]
I am working to throughly type `@wordpress/blocks` and `hpq` is a dependency of that package. I wanted to open the discussion on how best to improve the types produced by `hpq`.

There are a few options:

- Improve the types in the current JSDocs and generate a declaration file using TypeScript
- Move the package to TypeScript
- Publish a type declaration to DefinitelyTyped. This is my least favorite option, splitting the types from the source creates a difficult to maintain system where the types can get out of sync with the package.

I can do the work to integrate this, but I want to make sure there is interest before working on it.

**Comment by aduth** [comment]
Hi, thanks for the suggestion! I think it’d be great to add some first-party types. Personally, I’d prefer the JSDoc route, to have more control over the output package size, and since most of the work is already done (though I think there are a few issues in the existing type annotations that should be fixed up). If you’re willing to help with that, I’d really appreciate it. Otherwise I can plan to take a look at it in the next week or two.

**Comment by johnhooks** [comment]
Thanks for the response. I'll put a PR together using JSDocs.
